//
// ComputerSystem_data.h
//
// This file is intended to be eventually generated by a codegen tool
//
#ifndef __WS_COMPUTER_SYSTEM_H__
#define __WS_COMPUTER_SYSTEM_H__

#define WS_COMPUTER_SYSTEM_RESOURCE_URI \
		"http://schemas.dmtf.org/wsman/2005/06/cimv2.9/CIM_ComputerSystem"

// The resource is modeled as a struct
struct __ComputerSystem
{
	char* Caption;
	char* CreationClassName;
	char* Dedicated;
	char* Description;
	char* ElementName;
	char* EnabledDefault;
	char* EnabledState;
	char* HealthState;
	char* IdentifyingDescriptions;
	char* InstallDate;
	char* Name;
	char* NameFormat;
	char* OperationalStatus;
	char* OtherDedicatedDescriptions;
	char* OtherEnabledState;
	char* OtherIdentifyingInfo;
	char* PowerManagementCapabilities;
	char* PrimaryOwnerContact;
	char* PrimaryOwnerName;
	char* RequestedState;
	char* ResetCapability;
	char* Roles;
	char* Status;
	char* StatusDescriptions;
	char* TimeOfLastStateChange;
	
};
typedef struct __ComputerSystem ComputerSystem;


// Service endpoint declaration
int ComputerSystem_Enumerate_EP(WsContextH cntx, WsEnumerateInfo* enumInfo);
int ComputerSystem_Release_EP(WsContextH cntx, WsEnumerateInfo* enumInfo);
int ComputerSystem_Pull_EP(WsContextH cntx, WsEnumerateInfo* enumInfo);
ComputerSystem* ComputerSystem_Get_EP(WsContextH cntx);



SER_DECLARE_TYPE(ComputerSystem);
SER_DECLARE_EP_ARRAY(ComputerSystem);
DECLARE_SELECTOR_ARRAY(ComputerSystem);




void get_endpoints(GModule *self, void **data);
int init (GModule *self, void **data );
void cleanup( GModule *self, void *data );

#endif // __WS_COMPUTER_SYSTEM_H__
