//
// WsManThis_data.h
//
// This file is intended to be eventually generated by a codegen tool
//
#ifndef __WS_MAN_THIS_H__
#define __WS_MAN_THIS_H__

#define WS_MAN_THIS_RESOURCE_URI		"wsman:system/2005/06/this"

// The resource is modeled as a struct
struct __WsManThis
{
	char* Vendor;
	char* Version;
};
typedef struct __WsManThis WsManThis;

// Service endpoint declaration
WsManThis* WsManThis_Get_EP (WsContextH cntx);
WsDispatchInterfaceInfo *get_ep(void);

// Two macro below will declare 
// Serialization type info declaration for the resource
// extern struct __XmlSerializerInfo WsManThis_TypeInfo[];
// End point array declaration for the resource
// extern WsDispatchEndPointInfo WsManThis_EndPoints[];
SER_DECLARE_TYPE(WsManThis);
SER_DECLARE_EP_ARRAY(WsManThis);

#endif //__WS_MAN_THIS_H__
