//
// WsManThis_data.c
//
// This file is intended to be eventually generated by a codegen tool
//
//




#include "config.h"

#include "stdlib.h"
#include "stdio.h"
#include "string.h"
#include "ctype.h"

#include "ws_utilities.h"



#include "ws_errors.h"
#include "ws_xml_api.h"
#include "soap_api.h"
#include "xml_serializer.h"
#include "ws_dispatcher.h"

#include "wsman_this.h"

//
// ************ Serialization type information for resource ************
//
// It creates an array of items with name StateDescription_TypeInfo 
// It can be used in calls to WsSerialize and WsDeserialize 
//
SER_START_ITEMS("This", WsManThis)
	SER_STR("Vendor", 1, 1), 
	SER_STR("Version", 1, 1),
SER_END_ITEMS("This", WsManThis);


// ************** Array of end points for resource ****************
//
// Must follow general convention xxx_EndPoints
//
SER_START_END_POINTS(WsManThis)
	END_POINT_TRANSFER_GET(WsManThis, XML_NS_WS_MAN"/this"),
SER_FINISH_END_POINTS(WsManThis);






WsDispatchInterfaceInfo *get_ep() {
	WsDispatchInterfaceInfo *g_Interface;
	g_Interface = (WsDispatchInterfaceInfo *)malloc(sizeof(WsDispatchInterfaceInfo));
	
	g_Interface->flags = 0;
	g_Interface->actionUriBase = XML_NS_WS_MAN;
	g_Interface->wsmanSystemUri = NULL;
	g_Interface->wsmanResourceUri = WS_MAN_THIS_RESOURCE_URI;
	g_Interface->extraData = NULL;
	g_Interface->endPoints = WsManThis_EndPoints;
	
	return g_Interface;
}

