//
// WsManTest_data.c
//
// This file is intended to be eventually generated by a codegen tool
//
//

#include "config.h"

#include "stdlib.h"
#include "stdio.h"
#include "string.h"
#include "ctype.h"

#include <gmodule.h>

#include "ws_utilities.h"



#include "ws_errors.h"
#include "ws_xml_api.h"
#include "soap_api.h"
#include "xml_serializer.h"
#include "ws_dispatcher.h"

#include "wsman_test.h"

//
// ************ Serialization type information for resource ************
//
// It creates an array of items with name StateDescription_TypeInfo 
// It can be used in calls to WsSerialize and WsDeserialize 
//
SER_START_ITEMS("Test", WsManTestResult)
SER_UINT8("result1", 1, 1), 
SER_UINT8("result2", 1, 1), 
SER_END_ITEMS("Test", WsManTestResult);


SER_START_ITEMS("Test", WsManTest)
SER_STR("Test", 1, 1), 
SER_STRUCT("Result", 1, 1, WsManTestResult), 
SER_END_ITEMS("Test", WsManTest);


// ************** Array of end points for resource ****************
//
// Must follow general convention xxx_EndPoints
//

START_TRANSFER_GET_SELECTORS(WsManTest)
FINISH_TRANSFER_GET_SELECTORS(WsManTest);

SER_START_END_POINTS(WsManTest)
	END_POINT_TRANSFER_GET(WsManTest, XML_NS_WS_MAN"/test"),
    END_POINT_TRANSFER_ENUMERATE(WsManTest, XML_NS_WS_MAN"/test"),
    END_POINT_TRANSFER_PULL(WsManTest, XML_NS_WS_MAN"/test"),
    END_POINT_TRANSFER_RELEASE(WsManTest, XML_NS_WS_MAN"/test"),
SER_FINISH_END_POINTS(WsManTest);





void get_endpoints(GModule *self, void **data) 
{		
	WsDispatchInterfaceInfo *ifc = 	(WsDispatchInterfaceInfo *)data;	
    ifc->flags = 0;
    ifc->actionUriBase = XML_NS_WS_MAN;
    ifc->version = PACKAGE_VERSION;
    ifc->vendor = "Intel Corp.";
    ifc->displayName = "Test";
    ifc->notes = "Test Plugin";
    ifc->compliance = XML_NS_WS_MAN;
    ifc->wsmanSystemUri = NULL;
    ifc->wsmanResourceUri = WS_MAN_TEST_RESOURCE_URI;
    ifc->extraData = NULL;
    ifc->endPoints = WsManTest_EndPoints;
}


int init( GModule *self, void **data )
{
    return 1;
}

void
cleanup( GModule *self, void *data )
{
}

