#!/bin/bash
#
# run script for Python tests
#
# Usage: run <python> <dir> <file>
#
# Example (from build directory)
#    ../bindings/python/tests/run python3 ../bindings/python/tests xmlnode.py
#
(r=`realpath $0`;
 f=`dirname $r`;
 cd $2;
 PYTHONPATH=$f/../../../build/bindings/python LD_LIBRARY_PATH=$f/../../../build/src/lib $1 $3)
